name: code
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_storage: ^11.5.0
  http: ^1.1.0
  cloud_firestore: ^4.11.0
  firebase_ui_auth: ^1.9.1
  google_fonts: ^6.1.0
  provider: ^5.0.0
  quickalert: ^1.0.2
  google_sign_in: ^6.1.5
  persistent_bottom_nav_bar: ^5.0.2
  google_nav_bar: ^5.0.6
  pdf: ^3.10.6
  file_picker: ^6.1.1
  transparent_image: ^2.0.1
  path_provider: ^2.1.1
  printing: ^5.11.1
  share: ^2.0.4
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.0.4
  open_file: ^3.3.2
  smooth_page_indicator: ^1.1.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/


