// This file contains all the data used in the terms of use and privacy policy page.
Map<String, List<String>> settingsData = {
  "Terms of Use": [
    "Spare Spoon - Terms of Use",
    "Last Updated: 11-20-2023",
    "",
    "Welcome to Spare Spoon, a mobile application developed by Spare Spoon Inc. ('we,' 'us,' or 'our'). By accessing or using the Spare Spoon app, you agree to comply with and be bound by the following terms and conditions of use. If you do not agree to these terms, please do not use the app.",
    "",
    "1. Acceptance of Terms",
    "By using Spare Spoon, you acknowledge that you have read, understood, and agree to be bound by these Terms of Use. These terms may be updated by us from time to time without notice, and it is your responsibility to review them periodically.",
    "",
    "2. Use of Spare Spoon",
    "2.1 Recipe Generation",
    "Spare Spoon uses the ChatGPT API to generate new recipes based on user inputs. These recipes are provided for informational purposes only, and we do not guarantee their accuracy or suitability for any specific purpose.",
    "",
    "2.2 User Accounts",
    "To access certain features of Spare Spoon, you may be required to create a user account. You are responsible for maintaining the confidentiality of your account information and agree to accept responsibility for all activities that occur under your account.",
    "",
    "2.3 Recipe Management",
    "Spare Spoon allows users to save, edit, and manage recipes. You agree to use these features responsibly and not to engage in any unlawful or harmful activities.",
    "",
    "3. Intellectual Property",
    "All content and materials available on Spare Spoon, including but not limited to text, graphics, logos, button icons, images, audio clips, and software, are the property of [Your Company Name] or its content suppliers and are protected by international copyright laws.",
    "",
    "4. User Conduct",
    "While using Spare Spoon, you agree not to:",
    "- Violate any applicable laws or regulations.",
    "- Use the app for any unlawful or fraudulent purposes.",
    "- Interfere with or disrupt the operation of the app.",
    "- Upload, transmit, or distribute any content that is harmful, offensive, or violates the rights of others.",
    "",
    "5. Privacy Policy",
    "Your use of Spare Spoon is also governed by our Privacy Policy. Please review the policy to understand how we collect, use, and disclose your personal information.",
    "",
    "6. Termination",
    "We reserve the right to terminate or suspend your access to Spare Spoon at any time and for any reason without prior notice.",
    "",
    "7. Contact Us",
    "If you have any questions or concerns about these Terms of Use, please contact us at support@sparespoon.ca.",
    "",
    "Thank you for using Spare Spoon!",
  ],
  "Privacy Policy": [
    "Welcome to Spare Spoon!",
    "",
    "This Privacy Policy outlines how Spare Spoon collects, uses, and protects your personal information when you use our app.",
    "",
    "1. Information Collection:",
    "Spare Spoon collects user data for the purpose of providing recipe generation, management, and related services.",
    "",
    "2. Data Usage:",
    "Your data is used to personalize and improve your experience with Spare Spoon.",
    "We do not share your personal information with third parties without your consent.",
    "",
    "3. Security Measures:",
    "Spare Spoon employs security measures to protect your data from unauthorized access.",
    "It is important to keep your login credentials secure.",
    "",
    "4. Changes to Privacy Policy:",
    "Spare Spoon reserves the right to update this Privacy Policy.",
    "Users will be notified of any significant changes.",
    "",
    "By using Spare Spoon, you agree to the terms outlined in this Privacy Policy.",
    "",
    "Thank you for trusting Spare Spoon with your information!",
  ]
};
