// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR_lH0wFDmLRO37FpA8BY9N5rRNgKoHH4',
    appId: '1:747905689630:web:d817a60c258bd413b8260f',
    messagingSenderId: '747905689630',
    projectId: 'flutterauth-ff1a9',
    authDomain: 'flutterauth-ff1a9.firebaseapp.com',
    storageBucket: 'flutterauth-ff1a9.appspot.com',
    measurementId: 'G-LKF91K30WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnczjHBKNPIFziEpN4rCZxPwY35gqTeW4',
    appId: '1:747905689630:android:0aa714bf1be7b097b8260f',
    messagingSenderId: '747905689630',
    projectId: 'flutterauth-ff1a9',
    storageBucket: 'flutterauth-ff1a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRgusoZ3Ep3vRmJeB2GEf_EcdetFzGIfg',
    appId: '1:747905689630:ios:6612a41a448cd24db8260f',
    messagingSenderId: '747905689630',
    projectId: 'flutterauth-ff1a9',
    storageBucket: 'flutterauth-ff1a9.appspot.com',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRgusoZ3Ep3vRmJeB2GEf_EcdetFzGIfg',
    appId: '1:747905689630:ios:b856f3de38adb0b6b8260f',
    messagingSenderId: '747905689630',
    projectId: 'flutterauth-ff1a9',
    storageBucket: 'flutterauth-ff1a9.appspot.com',
    iosBundleId: 'com.example.code.RunnerTests',
  );
}
